<?php

//////////////////////////////////////////////////////////////////////
include("../../config/config.php"); 
//redirect ke halaman dashboard index jika sudah ada session
$halaman = "Man Power";
if(isset($_SESSION['user'])){

    include_once("../header.php");
?>
<!--konten isi -->
<div class="row">
    <div class="col-md-12">
        <div class="card ">

            <div class="card-header ">
                <div class="pull-right">
                    <a href="manpower.php" class="btn btn-default btn-round"><i
                            class="nc-icon nc-minimal-left"></i> Kembali</a>
                </div>
                <h4 class="card-title">Tambah Data Man Power</h4>
            </div>
            <div class="card-body ">
                <form method="post" action="proses.php" class="form-horizontal">
                    <div class="row">
                        <label class="col-sm-2 col-form-label">NPK</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="number" name="npk" id="npk" class="form-control"
                                    placeholder="tulis NPK (harus number)" required autofocus>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <label class="col-sm col-form-label">Nama Lengkap</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="text" name="nama" id="nama" class="form-control" placeholder="Nama Lengkap"
                                    required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Nick Name</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="text" name="nick" id="nick" class="form-control"
                                    placeholder="Autogenerated">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Tanggal Masuk</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="" name="tgl_masuk" id="tgl_masuk" class="form-control datepicker"
                                    value="tgl_masuk" placeholder="mm/dd/yyyy">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Jabatan</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <select name="jabatan" id="jabatan" class="form-control" title="Pilih Jabatan" required>
                                    <option value="TM">Team Member</option>
                                    <option value="TL">Team Leader</option>
                                    <option value="FR">Foreman</option>
                                    <option value="SV">Supervisor</option>
                                    <option value="MG">Dept Head</option>
                                    <option value="DH">Div Head</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <label class="col-sm-2 col-form-label">Status</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <select name="status" id="status" class="form-control" title="Pilih Jabatan" required>
                                    <option value="C1">Kontrak 1</option>
                                    <option value="C2">Kontrak 2</option>
                                    <option value="P">Permanent</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Shift</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <select name="shift" id="shift" class="form-control" title="Pilih Jabatan" required>
                                    <option value="A">A Shift</option>
                                    <option value="B">B Shift</option>
                                    <option value="N">N Shift</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Department</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <select name="dept" id="dept" class="form-control" data-size="7"
                                    data-style="btn btn-primary" title="dept" required>
                                    <option value="">Pilih Department</option>
                                    <?php
                                    /*
                                    //combobox department dari database table department 
                                      $sql_dept = mysqli_query($link, "SELECT * FROM department ORDER BY dept ASC") or die(mysqli_error($link));
                                      while($data_dept = mysqli_fetch_assoc($sql_dept)){
                                        echo '<option value="'.$data_dept['id_dept'].'">'.$data_dept['dept'].'</option>';
                                      }
                                      */
                                    ?>

                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Section</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <select name="sect" id="sect" class="form-control" required>
                                <option value="">Pilih Section</option>
                                    <?php
                                    /*
                                      $sql_sect = mysqli_query($link, "SELECT * FROM section ORDER BY section ASC") or die(mysqli_error($link));
                                      while($data_sect = mysqli_fetch_assoc($sql_sect)){
                                        echo '<option value="'.$data_sect['id_section'].'">'.$data_sect['section'].'</option>';
                                      }
                                    */
                                    ?>

                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Foreman</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <select name="group" id="group" class="form-control" data-size="7"
                                    data-style="btn btn-primary" title="group" required>
                                    <option value="">Pilih Group Foreman</option>
                                    <?php
                                    /*
                                    //combobox department dari database table department 
                                      $grp = mysqli_query($link, "SELECT * FROM groupfrm ORDER BY group_cord ASC") or die(mysqli_error($link));
                                      while($data_grp = mysqli_fetch_assoc($grp)){
                                        echo '<option value="'.$data_grp['id_group'].'">'.$data_grp['group_cord'].'</option>';
                                      }
                                      */
                                    ?>

                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Leader</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <select name="pos" id="pos" class="form-control" data-size="7"
                                    data-style="btn btn-primary" title="group" required>
                                    <option value="">Pilih Team Leader / Pos Kerja</option>
                                    <?php
                                    
                                    //combobox department dari database table department 
                                    /*
                                      $query_pos = mysqli_query($link, "SELECT * FROM pos_leader ORDER BY post_leader ASC") or die(mysqli_error($link));
                                      while($data_pos = mysqli_fetch_assoc($query_pos)){
                                        echo '<option value="'.$data_pos['id_post'].'">'.$data_pos['post_leader'].'</option>';
                                      }
                                      */
                                    ?>

                                </select>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <label class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-2">
                            <button type="submit" name="add" value="simpan" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
//untuk combobox organisasi
    $(document).ready(function() {

        $.ajax({
          type: 'POST', //method
          url: "dept/get_dept.php", //action          
          success: function(msg) {
            $("#dept").html(msg);
          }
        });
        $("#dept").change(function(){
      	var dept = $("#dept").val();
          	$.ajax({
          		type: 'POST',
              	url: "sect/get_sect.php",
              	data: {dept: dept},
              	cache: false,
              	success: function(msg){
                  $("#sect").html(msg);
                }
            });
        });
        $("#sect").change(function(){
        var sect = $("#sect").val();
        
          	$.ajax({
          		type: 'POST',
              	url: "group/get_group.php",
              	data: {sect: sect},
              	cache: false,
              	success: function(msg){
                  $("#group").html(msg);
                }
            });
        });
        $("#group").change(function(){
        var sect = $("#group").val();
        
          	$.ajax({
          		type: 'POST',
              	url: "pos/get_pos.php",
              	data: {sect: sect},
              	cache: false,
              	success: function(msg){
                  $("#pos").html(msg);
                }
            });
        });
    })
</script>


<?php
//footer
    include_once("../footer.php");


} else{
    echo "<script>window.location='".base_url('auth/login.php')."';</script>";
  }
  

?>