
<?php

//////////////////////////////////////////////////////////////////////
include("../../config/config.php"); 

//redirect ke halaman dashboard index jika sudah ada session
$halaman = "Man Power";
if(isset($_SESSION['user'])){

    include("../header.php");
?>
<!--konten isi -->
<!--modal box untuk edit MP-->
<!-- Scrollable modal
<div class="modal fade" data-backdrop="static" data-keyboard="false" id="editmp" tabindex="-1"
    aria-labelledby="ststicedit" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h5 class="modal-title" id="staticedit">Edit Data Man Power</h5>
                
            </div>
            <div class="modal-body">
                <form method="post" action="proses.php">
                    <label for="npk">NPK</label>
                    <div class="form-group">
                        
                        <input type="number" class="form-control" name="npk" id="npk" placeholder="tulis NPK (harus number)" required
                            autofocus>
                    </div>
                    <label for="nama">Nama Lengkap</label>
                    <div class="form-group">                        
                        <input type="text" class="form-control" name="nama" id="nama" placeholder="Nama Lengkap" required>
                    </div>                    
                    <label for="nick">Nick Name</label>
                    <div class="form-group">                        
                        <input type="text" class="form-control" name="nick" id="nick" placeholder="Nick Name" required>
                    </div>
					
					<label for="tgl_masuk">Tanggal Masuk</label>
                    <div class="form-group">
                        
                        <input type="text" class="form-control" name="tgl_masuk" id="tgl_masuk" class="form-control" placeholder="Autogenerated">
                    </div>
                    <div class="form-group">
                        <label for="tgl_masuk">Jabatan</label>
                        <select name="jabatan" id="jabatan" class="form-control" title="Pilih Jabatan" required>
                            <option value="TM">Team Member</option>
                            <option value="TL">Team Leader</option>
                            <option value="FR">Foreman</option>
                            <option value="SV">Supervisor</option>
                            <option value="MG">Dept Head</option>
                            <option value="DH">Div Head</option>
                        </select>
                    </div>
                    <div class="col-sm-10">
                        <div class="form-group">
                            <label for="jabatan">Status</label>
                            <select name="status" id="status" class="form-control" title="Pilih Jabatan" required>
                                <option value="C1">Kontrak 1</option>
                                <option value="C2">Kontrak 2</option>
                                <option value="P">Permanent</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="shift">Shift</label>
                        <select name="shift" id="shift" class="form-control" title="Pilih Jabatan" required>
                            <option value="A">A Shift</option>
                            <option value="B">B Shift</option>
                            <option value="N">N Shift</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="department">Department</label>
                        <select name="dept" id="dept" class="form-control" data-size="7" data-style="btn btn-primary"
                            title="Department" required>
                            <?php
                    //combobox department dari database table department 
                        $sql_dept = mysqli_query($link, "SELECT * FROM department ORDER BY dept ASC") or die(mysqli_error($link));
                        while($data_dept = mysqli_fetch_assoc($sql_dept)){
                        echo '<option value="'.$data_dept['id_dept'].'">'.$data_dept['dept'].'</option>';
                        }
                    ?>

                        </select>
                    </div>



                    <div class="form-group">
                        <label for="section">Section</label>
                        <select name="sect" id="sect" class="form-control" data-size="7" data-style="btn btn-primary"
                            title="Department" required>
                            <?php
                    //combobox department dari database table department 
                        $sql_sect = mysqli_query($link, "SELECT * FROM section ORDER BY section ASC") or die(mysqli_error($link));
                        while($data_sect = mysqli_fetch_assoc($sql_sect)){
                        echo '<option value="'.$data_sect['id_section'].'">'.$data_sect['section'].'</option>';
                        }
                    ?>

                        </select>
                    </div>
                    <div class="form-group">
                        <label for="group">Foreman</label>
                        <select name="group" id="group" class="form-control" data-size="7" data-style="btn btn-primary"
                            title="group" required>
                            <?php
                    //combobox department dari database table department 
                        $grp = mysqli_query($link, "SELECT * FROM groupfrm ORDER BY group_cord ASC") or die(mysqli_error($link));
                        while($data_grp = mysqli_fetch_assoc($grp)){
                        echo '<option value="'.$data_grp['id_group'].'">'.$data_grp['group_cord'].'</option>';
                        }
                    ?>

                        </select>
                    </div>
                    <div class="form-group">
                        <label for="pos">Leader</label>
                        <select name="pos" id="pos" class="form-control" data-size="7" data-style="btn btn-primary"
                            title="group" required>
                            <?php
                    //combobox department dari database table department 
                        $query_pos = mysqli_query($link, "SELECT * FROM pos_leader ORDER BY post_leader ASC") or die(mysqli_error($link));
                        while($data_pos = mysqli_fetch_assoc($query_pos)){
                        echo '<option value="'.$data_grp['id_post'].'">'.$data_grp['post_leader'].'</option>';
                        }
                    ?>

                        </select>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="submit" name="submit" class="btn btn-primary">Update</button>
            </div>
        </div>
    </div>
</div>
modal end-->


<!--card-->
<div class="row">
    <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
            <div class="card-body ">
                <div class="row">
                    <div class="col-5 col-md-4">
                        <div class="icon-big text-center icon-warning">
                            <i class="nc-icon nc-single-02 text-danger"></i>
                        </div>
                    </div>
                    <div class="col-7 col-md-8">
                        <div class="numbers">
                            <p class="card-category">Department</p>
                            <p class="card-title">4
                            <p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer ">
                <hr>
                <div class="stats">
                    <i class="fa fa-refresh"></i>
                    Update Now
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
            <div class="card-body ">
                <div class="row">
                    <div class="col-5 col-md-4">
                        <div class="icon-big text-center icon-warning">
                            <i class="nc-icon nc-single-02 text-warning"></i>
                        </div>
                    </div>
                    <div class="col-7 col-md-8">
                        <div class="numbers">
                            <p class="card-category">Section</p>
                            <p class="card-title">5
                            <p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer ">
                <hr>
                <div class="stats">
                    <i class="fa fa-refresh"></i>
                    Update Now
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
            <div class="card-body ">
                <div class="row">
                    <div class="col-5 col-md-4">
                        <div class="icon-big text-center icon-warning">
                            <i class="nc-icon nc-single-02 text-warning"></i>
                        </div>
                    </div>
                    <div class="col-7 col-md-8">
                        <div class="numbers">
                            <p class="card-category">Group</p>
                            <p class="card-title">5
                            <p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer ">
                <hr>
                <div class="stats">
                    <i class="fa fa-refresh"></i>
                    Update Now
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
            <div class="card-body ">
                <div class="row">
                    <div class="col-5 col-md-4">
                        <div class="icon-big text-center icon-warning">
                            <i class="nc-icon nc-single-02 text-warning"></i>
                        </div>
                    </div>
                    <div class="col-7 col-md-8">
                        <div class="numbers">
                            <p class="card-category">Leader</p>
                            <p class="card-title">5
                            <p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer ">
                <hr>
                <div class="stats">
                    <i class="fa fa-refresh"></i>
                    Update Now
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card ">
            <div class="card-header ">
                <h5 class="card-title">Daftar Man Power<li class="nc-icon nc-circle-10 pull-right"></li></h5> 
                <a href="" type="button" onClick="window.location.reload()" class="btn btn-md btn-success btn-outline-secondary btn-round btn-icon"><i
                            class="fa fa-refresh"></i></a>
                <a href="addmp.php" type="button" class="btn btn-md btn-default btn-round"><i class="fa fa-plus"></i> Tambah
                    Data</a>
                
                <span class="pull-right">
                    <form class="form-inline" action="" method="post">
                        <div class="form-group">
                        
                            <input type="text" name="pencarian" class="form-control"
                                placeholder="pencarian nama atau npk" style="width:250px">
                        </div>
                        <div class="form-gorup">
                            <button type="submit" class="btn btn-outline-secondary btn-primary"
                                aria-hidden="true"><i class="fa fa-search"></i></button>
                        </div>
                    </form>
                </span>
            </div>
			<form method="post" name="proses" action="">
                <div class="card-body ">
                    <div class="table-responsive" style="height:200">
                        <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th scope="col">No</th>
                                    <th scope="col">NPK</th>
                                    <th scope="col">Nama</th>
                                    <th scope="col">Nick Name</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Jabatan</th>
                                    <th scope="col">Tanggal Masuk</th>
                                    <th scope="col">Shift</th>
                                    <th scope="col">Pos</th>

                                    <th scope="col">Kontrol</th>
                                    <th scope="col">				
                                        <input type="checkbox" name="select_all" id="select_all" value="">																	
                                    </th>

                                </tr>
                            </thead>
                            <tbody>




                                <?php
                        //////////////////////////////////////////////////////////////////////
                        //untuk kondisi awal
                        
                        $batas = 50; //untuk mengatur batas halaman perpage
                        $hal = @$_GET['hal']; //apakah halaman ada di url
                        if(empty($hal)){
                            //jika tiak ada query string yang dikirim, maka masukan nilai 0 ke variabel posisi, dan set hal dengan nilai 1
                            $posisi = 0;
                            $hal = 1;
                        } else {                 
                            $posisi = ($hal - 1) * $batas; //jika tombol pagination tidak diklik maka posisi 0
                        }

                        //kalo ada inputan post search
                        $no = 1;
                        if($_SERVER['REQUEST_METHOD'] == "POST"){
                            //jika ada masukan parameter hasil pencarian kedalam variabel $pencarian
                            $pencarian = trim(mysqli_real_escape_string($link, $_POST['pencarian']));
                            //jika pencarian ada, masukan hasil queri pencarian ke dalam variabel query jumlah
                            if($pencarian !== ''){
                                $sql = "SELECT * FROM karyawan WHERE npk LIKE '%$pencarian%'or nama LIKE '%$pencarian%'";
                                $query_mp = $sql;
                                $queryjml = $sql;
                            //jika inputan kosong , masukkan  nilai posisi + 1 ke dalam no    
                            } else{
                                $query_mp = "SELECT * FROM karyawan LIMIT $posisi, $batas";
                                $queryjml = "SELECT * FROM karyawan";
                                $no = $posisi + 1;
                            }
                        //jika tidak ada inputan pencarian tidak dilakukan, masukkan  nilai posisi + 1 ke dalam no     
                        } else {
                            $query_mp = "SELECT * FROM karyawan LIMIT $posisi, $batas";
                            $queryjml = "SELECT * FROM karyawan";
                            $no = $posisi + 1;
                        }


                        $data_mp = mysqli_query($link, $query_mp);
                        //jika Query gagal
                        if(!$data_mp){
                            die("Query gagal dijalankan : ".mysqli_errno($link)."-".mysqli_error($link));
                        }

                        //ambil hasil query mysql
                        $no_urut = 0;
                        if(mysqli_num_rows($data_mp) > 0){
                            while($tampil_mp = mysqli_fetch_assoc($data_mp)){
                                $no_urut++;

                                ?>

                                <?php    
                                echo "<tr><td>$no_urut</td>";
                                echo "<td>$tampil_mp[npk]</td>";
                                echo "<td>$tampil_mp[nama]</td>";
                                echo "<td>$tampil_mp[nama_depan]</td>";
                                echo "<td>$tampil_mp[status]</td>";
                                echo "<td>$tampil_mp[jabatan]</td>";
                                echo "<td>$tampil_mp[tgl_masuk]</td>";
                                echo "<td>$tampil_mp[shift]</td>";
                                echo "<td>$tampil_mp[id_area]</td>";
                                
                                echo "<td>";
                                ?>

                                <!--<a href="edit_mp.php?npk=--><?php //echo $tampil_mp['npk']?>
                                <!---" class="btn btn-sm btn-outline-default"><span class="fa fa-edit"></span></a>-->
                                <a href="edit_mp.php?npk=<?=$tampil_mp['npk'];?>" type="button" class="btn btn-sm btn-outline-primary btn-round btn-icon" ><i class="fa fa-edit"></i></a>


                                <!--tombol modal inactive
                                <a class="btn btn-sm btn-outline-default" id="tomboledit" data-toggle="modal" data-target="#editmp"
                                    data-npk="<?//=$tampil_mp['npk']?>" data-nama="<?//=$tampil_mp['nama']?>"
                                    data-nick="<?//=$tampil_mp['nama_depan']?>" data-status="<?//=$tampil_mp['status']?>"
                                    data-jabatan="<?//=$tampil_mp['jabatan']?>" data-masuk="<?//=$tampil_mp['tgl_masuk']?>"
                                    data-shift="<?//=$tampil_mp['shift']?>" data-pos="<?//=$tampil_mp['id_area']?>"><i
                                        class="fa fa-edit"></i></a>
                                        -->

                                <a href="del_mp.php?npk=<?=$tampil_mp['npk']?>"
                                    onclick="return confirm('yakin akan menghapus <?=$tampil_mp['nama']?> dengan NPK <?=$tampil_mp['npk']?> dari database?')"
                                    class="btn btn-sm btn-outline-danger btn-round btn-icon"><i class="fa fa-trash"></i></a>
                                <button type="button" class="btn btn-sm btn-outline-primary btn-round">Absensi</button>

                                
                            <?php
                            echo "</td><td>";
                            ?>
                                <input type="checkbox" name="checked[]" id="checked" class="check" value="<?=$tampil_mp['npk']?>"></td></tr>

                            <?php

                            }
                                

                            } else{
                                
                                echo "<tr><td colspan=\"9\">Data tidak ditemukan</td>";

                                
                            }

                        ?>



                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer ">
                        <?php
                    ////////////////////////////////
                    //pagination dan result pencarian
                    //jika pencarian ada, maka tampilkan total hasil pencarian dari rows database
                    if(empty($_POST['pencarian'])){?>
                        <div style="float:left;">
                            <?php
                                $jml = mysqli_num_rows(mysqli_query($link, $queryjml));
                                echo "Jumlah data :  $jml";
                                ?>
                        </div>
                        <div style="float:right">
                            <ul class="pagination pagination-sm">
                                <?php
                                    $jml_hal = ceil($jml / $batas);
                                    for ($i=1; $i <= $jml_hal ; $i++) {
                                        if($i != $hal){
                                            echo "<li class=\"page-item\"><a href=\"?hal=$i\" class=\"btn btn-sm btn-no-border btn-round btn-icon\">$i</a></li>";
                                        } else {
                                            echo "<span class=\"btn btn-sm btn-default btn-round btn-icon\"><a>$i</a></span>";
                                        }                                    
                                    }
                                    ?>
                            </ul>
                        </div>

                        <?php
                    } else { 
                        echo "<div style=\"float:left\">";
                        $jml = mysqli_num_rows(mysqli_query($link, $queryjml));
                        echo "ditemukan <strong>$jml</strong> hasil pencarian ";
                        echo "</div>";
                        
                    }
                    
                    
                    ?>


                        <div class="stats">

                        </div>
                    </div>
                </div>
			</form>
        </div>
    </div>
</div>




    <?php


mysqli_free_result($data_mp);

// tutup koneksi dengan database mysql
mysqli_close($link);

?>

    <?php
//footer
    include_once("../footer.php");

} else{
    echo "<script>window.location='".base_url('auth/login.php')."';</script>";
  }
  

?>